### ISSUE TITLE
Nicht alle Redebeiträge werden korrekt geparsed

### ISSUE THREAD

**Issue by rknall** [badlogic/woswormeileistung#2]
Es gibt offenbar unterschiedliche Formate bei den Texten. Bei https://woswormeileistung.marioslab.io/person/83101 sind im Redebeitrag der Zwischenrufe des Hr. Mahrer ein Parsingfehler enthalten, wo Fr. Maurer einmal nicht korrekt geparsed wurde. Ich nehme mal an, weil kein Doppelpunkt auf den Namen folgt.

Auch wurde die Partei des Hr. Mahrer nicht erfasst.

Ansonsten geniales Tool

**Comment by badlogic** [comment]
Bitte immer konkrete Textstellen angeben, sonst wirds ein guessing game.

In dem Fall meinst du ws.:

Abg. Maurer – ein Schriftstück in die Höhe haltend –: Haben Sie es selbst
gelesen?

Das : fehlt nicht, sondern ist zu weit vom Namen der Abg. entfernt.
Generell folgen die Stenograph:innen strikten Regeln bei der Markierung von
Zwischenrufen. Das ist hier im Quelltext nicht der Fall. Derer "Fehler"
gibt es nur wenige. Den Parser dafür anzupassen hätte evtl. die Folge, das
invalide Konstrukte ebenfalls fälschlich als Zwischenruf gewertet werden.

Ich behalts am einmal am Radar. Prinzipiell ist es leider unmöglich auf
diesen Daten alles zu 100% korrekt zu parsen, da die Quelldokumente HTML
Exporte aus MS Word heraus sind und dementsprechend Oarsch sind...

**Comment by rknall** [comment]
Ja, das war die Stelle. Ist mir schon klar, war kurz am Überlegen das per Screenshot anzugeben. Wäre es eventuell möglich einen direkten Link zu den Redebeiträgen anzulegen? Würde es leichter machen hier einen zu verlinken.

Das mit dem Parsen verstehe ich absolut, es werden auch andere Varianten auftreten. Generell wieder einmal ein Supertool aus dem Mario Lab ;-)

**Comment by badlogic** [comment]
Ja, direkt Link zum Beitrag ist auf meiner TODO :)
